// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W26Week9CodeFirstApproach;

#nullable disable

namespace W26Week9CodeFirstApproach.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20260311184951_ChangeStudentNameToName")]
    partial class ChangeStudentNameToName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W26Week9CodeFirstApproach.Standard", b =>
                {
                    b.Property<int>("StandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandardId"));

                    b.Property<string>("StandardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StandardId");

                    b.ToTable("Standards");

                    b.HasData(
                        new
                        {
                            StandardId = 1,
                            StandardName = "Standard 1"
                        },
                        new
                        {
                            StandardId = 2,
                            StandardName = "Standard 2"
                        },
                        new
                        {
                            StandardId = 3,
                            StandardName = "Standard 3"
                        },
                        new
                        {
                            StandardId = 4,
                            StandardName = "Standard 4"
                        },
                        new
                        {
                            StandardId = 5,
                            StandardName = "Standard 5"
                        });
                });

            modelBuilder.Entity("W26Week9CodeFirstApproach.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("StandardId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("StudentId");

                    b.HasIndex("StandardId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            StandardId = 2,
                            StudentName = "John"
                        },
                        new
                        {
                            StudentId = 2,
                            StandardId = 3,
                            StudentName = "Anne"
                        },
                        new
                        {
                            StudentId = 3,
                            StandardId = 1,
                            StudentName = "Mark"
                        },
                        new
                        {
                            StudentId = 4,
                            StandardId = 1,
                            StudentName = "Sam"
                        },
                        new
                        {
                            StudentId = 5,
                            StandardId = 5,
                            StudentName = "Alice"
                        });
                });

            modelBuilder.Entity("W26Week9CodeFirstApproach.Student", b =>
                {
                    b.HasOne("W26Week9CodeFirstApproach.Standard", "Standard")
                        .WithMany("Students")
                        .HasForeignKey("StandardId");

                    b.Navigation("Standard");
                });

            modelBuilder.Entity("W26Week9CodeFirstApproach.Standard", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
